name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.x.x

      - name: Install
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Build Typedoc
        run: bun run doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      - uses: JS-DevTools/npm-publish@v3
        with:
          package: build/
          registry: "https://npm.pkg.github.com"
          token: ${{ secrets.GITHUB_TOKEN }}
