name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.x.x

      - name: Install
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test

      - uses: JS-DevTools/npm-publish@v3
        with:
          package: build/
          registry: "https://npm.pkg.github.com"
          token: ${{ secrets.GITHUB_TOKEN }}
