name: release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get token
        id: lib-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Run release-please-action
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          token: ${{ steps.lib-token.outputs.token }}
